### ISSUE TITLE
Improve the 'Start' page of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#25]
This ticket is for the **Start** page of the Open Badges 101 website: http://badges.thinkoutloudclub.com/modules/discuss/discuss/

Got a suggestion of what we could add / improve? Great! Add your comments below.

**Comment by dajbelshaw** [comment]
[Laura Hilliger](http://twitter.com/epilepticrabbit) suggested we include a diagram for the Know / Do / Reflect flow on the Start page. Perhaps something like this?

![Know / Do / Relect](http://www.edutopia.org/sites/default/files/styles/content_image_breakpoints_theme_edutopia_desktop_1x/public/content/df/lenz-assessmentdeeperlearning-triangle300.gif)

Unsure of license for above image, but from [this Edutopia article](http://www.edutopia.org/blog/how-assessment-can-lead-to-deeper-learning-bob-lenz). Perhaps @bryanmathers has some ideas...

**Comment by Wentale** [comment]
What does the triangle in the middle represent? I think it needs to have arrows....more directional to indicate that "reflect" will help the "know" and "Do" is critical. Will search for supporting information and post back here.
Whatever diagram is chosen should be reflected in the badge system for the course.

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
