### ISSUE TITLE
Improve the 'What' module of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#26]
This ticket is for the **What** module of the Open Badges 101 website: http://badges.thinkoutloudclub.com/modules/what/intro/

Got a suggestion of what we could add / improve? Great! Add your comments below.

**Comment by Wentale** [comment]
The heading seems to contradict....open badges ARE digital badges? The statement from badges alliance just says that open badges take digital badges 'one step' further. Is that just the backpack concept? Also the term metadata (built in data) could be introduced here....in relation the the badges anatomy diagram.

**Comment by dajbelshaw** [comment]
Thanks @Wentale - got a favourite explanation of metadata?

**Comment by Wentale** [comment]
Metadata - data about data.
The first para here http://www.niso.org/publications/press/UnderstandingMetadata.pdf describes it simply and neatly.

**Comment by dajbelshaw** [comment]
Perfect, @Wentale! Thank you. :)

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
