### ISSUE TITLE
Improve the 'Why' module of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#27]
This ticket is for the **Why** module of the Open Badges 101 website: http://badges.thinkoutloudclub.com/modules/why/intro/

Got a suggestion of what we could add / improve? Great! Add your comments below.

**Comment by dajbelshaw** [comment]
From [Paul Martin](https://groups.google.com/forum/#!topic/openbadges/hj4HW0M9R80):

---

(initial thoughts on the <draft> central module: WHY)

The graphic of a young lad is nicely composed, but there’s something about the choice of words down the right - I am not convinced that such qualities are easy to measure and produce a taxonomy for. Lately I have been appreciating Adult Education and wonder if there is a more practically oriented picture, or two, to provide a different theme to this section; maybe as simple as a change in the words used. 

I have not been following the Open Badges debate closely but feel that there ought to be a breakdown under the first bullet point. I would venture various scenarios (which I admit may well have been described elsewhere):
- A CPD log of achievement for a teacher at say a FE College
- the steps required to master basic Javascript
- required steps for an adult job returner

I appreciate that its all pre-alpha and that the pics used through the module have a consistent style which may (or may not) have lead to a precipitate choice of image.

Good start ...

**Comment by paulmartin42** [comment]
I am 80% of the way through my free Linda trial of all their materials at LinkedIn. They don't seem to do certificates & thus despite my holiday month cramming I have no proof or concrete motivation for finishing the goal I set out to achieve, but looks like I will not. 

The mobile app creation process is complex and without a syllabus or human tutorial advice is frustrating. The odd badge in lieu of my working software would have been nice.

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
