### ISSUE TITLE
Improve the 'Resources' page of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#29]
This ticket is for the **Resources** page of the Open Badges 101 website: http://badges.thinkoutloudclub.com/modules/resources/introduction/

Got a suggestion of what we could add / improve? Great! Add your comments below.

**Comment by Enkerli** [comment]
For starters, the link is invalid, as you’ve changed it to resources…
http://badges.thinkoutloudclub.com/modules/resources/introduction/
There are so many interesting resources on badges and it would be inefficient to just list them. But a curated list of references could indeed make a lot of sense.
For instance, it’d be important to have a section on badging initiatives. Maybe something inspired by Hickey’s [DPD](http://dpdproject.info)?

**Comment by dajbelshaw** [comment]
Thanks, updated link. :)

Happy to structure this however you see fit. Other sections have Know / Do / Reflect, but we can separate things out in this section however we see fit.

**Comment by Wentale** [comment]
I could suggest that the Resources are split into the Reflect area of each segment.

**Comment by dajbelshaw** [comment]
Interesting, @Wentale - so we wouldn't need a **Resources** section then?

**Comment by Wentale** [comment]
Unless there are general Resources that don't fit into the other sections. (What are they doing there, then?). I find that a Resources list is something that is left untouched or "if I have time"....if it's incorporated into Reflect and made relevant it keeps the integrity of the course as well as get good viewings.

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
