### ISSUE TITLE
Improve the 'Discuss' page of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#30]
This ticket is for the **Discuss** page of the Open Badges 101 website: http://badges.thinkoutloudclub.com/modules/discuss/discuss/

Got a suggestion of what we could add / improve? Great! Add your comments below.

**Comment by Enkerli** [comment]
While the Google Group can be a great place to connect likeminded people, isn’t there potential for a clash between learners taking this Badges 101 course and the well-seasoned badgers already in the community space?

**Comment by dajbelshaw** [comment]
Thanks @Enkerli but we're not interested in creating a new community and, as someone who has been part of that group since it's inception, it's _particularly_ important that we welcome newbies. 

I agree, however, that a dedicated thread for those introducing themselves to the Google Group might be in order. :)

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
