### ISSUE TITLE
Improve miscellaneous elements of Open Badges 101

### ISSUE THREAD

**Issue by dajbelshaw** [thinkoutloudclub/badge-course#31]
This ticket is for everything not covered by the other tickets for the Open Badges 101 website. 

_(e.g. Mobile view not working? Text need updating? Colour scheme not great?)_

**Got a suggestion of what we could add / improve?** Great! Add your comments below.

**Comment by Wentale** [comment]
The Intro, know, do, reflect doesn't match the bullet points on the front page...it's confusing trying to match up which page with github page.

**Comment by dajbelshaw** [comment]
Thanks @Wentale but I'm not sure what you mean? The know / do / reflect flow is within each module. So the **What** module contains:
- [Intro](https://github.com/thinkoutloudclub/badge-course/blob/gh-pages/modules/what/_posts/2000-01-01-intro.markdown)
- [Know](https://github.com/thinkoutloudclub/badge-course/blob/gh-pages/modules/what/_posts/2000-01-02-know.markdown)
- [Do](https://github.com/thinkoutloudclub/badge-course/blob/gh-pages/modules/what/_posts/2000-01-03-do.markdown)
- [Reflect](https://github.com/thinkoutloudclub/badge-course/blob/gh-pages/modules/what/_posts/2000-01-04-reflect.markdown)

**Comment by Wentale** [comment]
Just trying to match up the overall unit design (What/Why/How/Resources/Discuss) with the github links. I like the Know/Do/Reflect within each one of those areas but the github link needs to include the What/Why.... format so it's plain what we are commenting on.

**Comment by dajbelshaw** [comment]
Ah, gotcha. Didn't want to make it too complicated to begin with! I'll update each ticket with a sub-ticket. :)

**Comment by paulmartin42** [comment]
Do I get an (incentive) badge for my efforts ?

**Comment by dajbelshaw** [comment]
Closing this issue in favour of the new etherpad. We'll keep ideas in etherpad to lower the barrier to entry while development work will continue in GitHub.

More here: http://bit.ly/OB101-build
